name = "filrb"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Filrb"]
testRunner = "Test"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Filrb"

[[lean_lib]]
name = "Test"
